### ISSUE TITLE
Device with libusb-win32 also shows up as WinUSB device when installed with Zadig

### ISSUE THREAD

**Issue by tibel** [pbatard/libwdi#10]
I used zadig v2.0.1.160 to install a libusb-win32 (v1.2.6.0) driver.
The driver folder also contains "winusbcoinstaller2.dll" and when using LibUsbDotNet the device is shown in LibUsb and WinUsb registry.

I'm new to this installer and want to know if this is intended behavior or a bug?

**Comment by pbatard** [comment]
I don't think I'll ever get a chance to look at this, and nobody seems to have reported anything similar since 2012 &rarr; Closing.
