### ISSUE TITLE
Can I get older versions of the program?

### ISSUE THREAD

**Issue by ABrowserMain** [pbatard/libwdi#112]

**Comment by pbatard** [comment]
1. What "program"? Zadig???
2. The website for Zadig does have an explicit link for [other versions](http://zadig.akeo.ie/downloads/).
3. If this is not for Zadig, or if it's for a version not provided on the website then no. Then again, libwdi is 100% Open Source, so if you want an older version, you can compile it yourself. Just don't expect __others__, who may be quite busy, to do that work for you.

**Comment by ABrowserMain** [comment]
nvm it doesn't work anyways
