### ISSUE TITLE
Batch installing with Zadig

### ISSUE THREAD

**Issue by dylanede** [pbatard/libwdi#116]
It would be useful if Zadig could be run in a silent mode to install a list of devices. This could be done as an extension to the device config file format (to support multiple devices, and the ability to specify the driver to use) in combination with a command line switch.

**Comment by pbatard** [comment]
I think you may want to look into `wdi-simple`, which is a commandline equivalent to what Zadig is doing.
This is part of the [samples provided by libwdi](https://github.com/pbatard/libwdi/tree/master/examples) (of which Zadig is only one example).

Many people have been using wdi-simple to achieve the kind of thing that you want.
Of course, you will have to recompile it yourself.

**Comment by PetteriAimonen** [comment]
Is there a particular reason why `wdi-simple` is not included in the precompiled releases?

**Comment by Anutrix** [comment]
Same here. Adding cmd support to zadig for advanced users seems like a really useful option.

**Comment by pbatard** [comment]
This would take time. Which I don't have for this specific request.
