### ISSUE TITLE
Download fails with "Failed - Network error"

### ISSUE THREAD

**Issue by rahulgm** [pbatard/libwdi#118]
Same as issue https://github.com/pbatard/libwdi/issues/109.

Downloading http://zadig.akeo.ie/downloads/zadig-2.3.exe failed with same error. Have checked it on at least two different networks.

Please look into it.

**Comment by pbatard** [comment]
Issue is on your side. Server logs show no gaps in the ability for people to download Zadig around the time you reported the issue, and I also see nothing to indicate that there was any network issue on our side.
