### ISSUE TITLE
Is it possible to change the provider name?

### ISSUE THREAD

**Issue by karel-3d** [pbatard/libwdi#124]
Hello,

is it possible to change the provider name of the driver from "libwdi" to something else? (even with editing the source code)

Thanks

**Comment by pbatard** [comment]
The whole project is Open Source, so yes, as long as you respect the license, you can do whatever you want.

You probably want to change [this](https://github.com/pbatard/libwdi/blob/master/libwdi/winusb.inf.in#L14).

**Comment by karel-3d** [comment]
Thank you, I was asking about the place in the inf. Amazing
