### ISSUE TITLE
USB not working properly after driver instalation

### ISSUE THREAD

**Issue by ffinacio** [pbatard/libwdi#135]
After running zadig-2.4.exe in my Windows 10 Pro OS build 17134.165 my USB Hub is opening all four terminations in a strange behaviour requesting format for non existing devices and USB printer is not working. 
I was using zadig to install a driver on my Netduino 3 MF what with success.
Could you help me to recover USB drivers.

**Comment by pbatard** [comment]
https://github.com/pbatard/libwdi/wiki/FAQ#Help_Zadig_replaced_the_driver_for_the_wrong_device_How_do_I_restore_it
