### ISSUE TITLE
zadig.akeo.ie "can’t be reached"

### ISSUE THREAD

**Issue by esozer** [pbatard/libwdi#148]
This site can’t be reached zadig.akeo.ie refused to connect.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED

Ping returns:

ping zadig.akeo.ie

Pinging zadig.akeo.ie [199.38.82.138] with 32 bytes of data:
Reply from 199.38.82.138: bytes=32 time=24ms TTL=55
Reply from 199.38.82.138: bytes=32 time=24ms TTL=55
Reply from 199.38.82.138: bytes=32 time=25ms TTL=55
Reply from 199.38.82.138: bytes=32 time=24ms TTL=55

Ping statistics for 199.38.82.138:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 24ms, Maximum = 25ms, Average = 24ms

**Comment by pbatard** [comment]
Fixed. Thanks for the report.
