### ISSUE TITLE
Not an issue, but Thanks for good documentation!

### ISSUE THREAD

**Issue by E3V3A** [pbatard/libwdi#154]
I really appreciate your Wiki entry about [Reuse](https://github.com/pbatard/libwdi/wiki/Reuse)! :heart:  
If only more library repos would bother to add this kind of quality info, github would be a truly amazing place. Thanks again for writing useful Wiki entries and usage scenarios. :+1:  :1st_place_medal:  :100:

**Comment by pbatard** [comment]
Thanks. Unfortunately this is probably a bit outdated by now, as I haven't had a chance to maintain this page in years. But I'm glad to hear you found it useful.
