### ISSUE TITLE
Zadig cli

### ISSUE THREAD

**Issue by ckc-petersen** [pbatard/libwdi#156]
Hi I was wondering if the wdi-simple can be compiled to run in command line without a gui as I am planning on using it in a script.

thanks in advance

**Comment by pbatard** [comment]
Well, wdi-simple is __already__ CLI. There's no GUI. There's also a Zadic in the samples, which is (more or less) the CLI version of Zadig.

As I believe I have answered your question, I will close this issue. If you have further queries, please make sure you try to compile the samples first, to see what they can do.
