### ISSUE TITLE
Common HID mouse query solution

### ISSUE THREAD

**Issue by robbitybobbity** [pbatard/libwdi#160]
Hi,
Just a note. I had the same issue as a lot of people - trashing my own wireless mouse and keyboard with Zadig because I didn't know what I was doing :/

Anyway - I read the same thing over and over about people uninstalling the mouse driver, which didn't work. 
The method below eventually worked for me, so might help save someone some time. 

When your wireless mouse stops working after you do something dumb in Zadig, it may not actually be the mouse driver you overwrote, but the USB RECEIVER driver (the driver for the little USB dongle). So you can delete and uninstall the mouse driver all night with no success. 

But if you look for a generic "USB Receiver" in the device manager list, then right click on that, uninstall with the "delete driver" option clicked (as suggested by Dr. Zadig), then unplug and replug the mouse dongle (aka the receiver), it should all be good. Mine came back to life immediately.

What would be better would be if the windows device manager actually gave the name of the driver in the list (or better - let you search by driver name) so you could see which one had the WinUSB attached to it so you could see which HID you overwrote like a drunk noob.
Cheers,
Drunk Noob

**Comment by pbatard** [comment]
Note: You can see the name of the driver being used from Device Manager: Go to details and look for the `Service` or `Device stack` variables. They should give you the name of the driver being used.

Anyway, I will close this issue, which hopefully will be found by others running into the same problem.
