### ISSUE TITLE
External disk lost connection after my mistake (Western Digital My Passport unit)

### ISSUE THREAD

**Issue by Yoshideking** [pbatard/libwdi#164]
Hi,

so I'm not well versed on computer but I'm not new on this, so I hope I can explain myself.

So I needed to connect my Nintendo Switch to the computer, and I think I made a mistake at first because I didn't replace the "device" at first, so I installed libusbK (v.3.0.7.0) on My Passport 25E2 (Western Digital external disk). And now I can't get to gain access again with this device.

The Western Digital utility doesn't recognize it. So I think I could test other drivers with zadig, but none seems to work.

Could you please lend me a hand, please?

I'm on Windows 10.

Data zadig gives me:
My Passport 25E2
Driver: WinUSB (v.6.1.7600.16385)
USB ID: 1058 25E2
WCID: X

I know I mess it up, but I can repair it with your advice.

Edit:
Well I founded on the device administrator under: port COM4 and LPT
I uninstall the driver, but I still doesn't recognice it.

I can read the external disk on other computer, but not on mine anymore.
I think this has nothing to do with your software. So I''m reading all I can. I'm sry for the trouble.

Now he external disk appears on: USB devices on device administrator, and it says it has it's drivers updated. But it still doesn't shows up.
I did mess it up...

How can I remove it's relationship to libwdi drive?
Device manager says that the disk is attached to this file on my PC: USB\VID_1058&PID_25E2 (libwdi autogenerated)

Since libwdi is the name of this proyect, I have to ask why it autogenerates himself when I remove and erase it. I really need to make it forget about this libdwi driver.

**Comment by pbatard** [comment]
https://github.com/pbatard/libwdi/wiki/FAQ#Help_Zadig_replaced_the_driver_for_the_wrong_device_How_do_I_restore_it

**Comment by Yoshideking** [comment]
Hi, I did everything and after this step (4):

                "Once the uninstallation is complete, unplug and replug your device. The original system driver should now be reinstalled. In our case, we would see the Flash Drive reappearing under the Disk drives category, which is what we want."

The device stills appears under:

driver provider: libwdi
driver date: 10.feb.2017
digital firm: USB\VID_1058&PID_25E2 (libwdi autogenerated)

**Comment by pbatard** [comment]
The trick is to insist and make sure you repeat the process for all the USB ports you might have plugged your device in until the libwdi installed driver disappears.

I have never seen a system where what I explained above didn't work after persisting.

Alternatively, you can look around for driver uninstallation applications (but you will have to do your homework, as I'm not going to help you with that).

**Comment by Yoshideking** [comment]
Problem solved thx to the tutorial linked. I just unninstal many times until it works.
I donne it, thanks. The tricks is to insist because I reinstall the driver many times with zadig.

My bad, thanks, your help is much appreciated.
