### ISSUE TITLE
Com port not showing up after Platform IO esp-prog install 

### ISSUE THREAD

**Issue by JamesNewton** [pbatard/libwdi#167]
Hi, and thanks for writing this. I'm trying to get the WinUSB driver installed on my Windows 7 PC to use the esp-prog debugger with Platform.IO in VSCode for the ESP32. I'm following the directions here:
https://www.youtube.com/watch?v=psMqilqlrRQ
which leads me to here:
https://docs.platformio.org/en/latest/plus/debug-tools/esp-prog.html
which leads me to here:
https://community.platformio.org/t/esp32-pio-unified-debugger/4541/20
which works perfectly until step 7 where I'm supposed to use Zadig to replace the Dual RS232-HS (Interface 0) with WinUSB

I can't seem to get the WinUSB driver installed and working. I got to "USB Serial Converter A" and "...B" in the USB controllers list, then ran Zadig on "Dual RS232-HS (Interface 0)" but it hung. Waited 10 minutes "(Not responding)". 

I restarted the PC, tried it again, and it said it worked. Unplugged, plugged in, and now I only have "USB Serial Converter A" (as expected) but no com port. Re-installing the driver via Zadig appears to work, but nothing shows up again under com ports. "Dual RS232-HS (Interface 0)" is now listed under "USB devices" and no ports. 

Any ideas? or where else can I ask?

**Comment by pbatard** [comment]
Sorry, I'm afraid I don't know anything about the type of hardware you are trying to install a generic USB driver from. Please bear in mind that, just like WinUSB is a generic USB driver that is designed to be usable by pretty much any USB device out there, the same is true for libwdi/Zadig (which means that, in most case, the developers of the software will have little of no knowledge whatsoever of the specifics of the hardware you are trying to use, and no means of testing it either). Therefore, if you have an issue, you are better off asking the question of forums that are dedicated to the type of hardware you use.

As a result, considering that nobody chimed in in 2 weeks, I will close this issue.
