### ISSUE TITLE
Zadig drivers Freeshuttercount - Corsair K95 Rollback issues

### ISSUE THREAD

**Issue by Dragonfyr** [pbatard/libwdi#170]
Installed the FreeShuttercount software. 
Installed the Zadig software driver thing. 
Accidently clicked keyboard change driver in Zadig. 
Spent the next hour going around in circles trying to reinstall my keyboard... with no keyboard! NOT fun in the slightest. 

My fix:
Uninstall Shutter software.
Uninstall zadig thing.
Uninstall Corsair iQue (K95) software.
Clean registry. (Used CCleaner).
Shut down.
Place keyboard usb cables (there's 2), into different usb ports. 
Boot back up. 
Download iQue software and reinstall it (I used my headset mic+Google to search for the software). 
Reboot. 
Keyboard works! 
My head hurts.

Good software for shutter count info. 
Bad zadig software feature that you can't roll back drivers. (Also read on some pages that people had the same issue). 

Thanks anyway

**Comment by pbatard** [comment]
See also https://github.com/pbatard/libwdi/wiki/FAQ#Help_Zadig_replaced_the_driver_for_the_wrong_device_How_do_I_restore_it

I have to point out that Zadig should have produced a prominent __extra__ warning about replacing the driver for your keyboard, precisely to avoid this situation. But there's really only so much I can do in the app to prevent users from shooting themselves in the foot...
