### ISSUE TITLE
FC connection problem

### ISSUE THREAD

**Issue by hnter02** [pbatard/libwdi#178]
When I connect my Flight Controller to my pc I cannot see it listed in Zadig.I should be seeing something like stm32 BOOTLOADER but it just doesnt show up for me.I have installed other drivers and restarted my pc before opening Zadig.Please help.Thanks

**Comment by pbatard** [comment]
![Image1](https://user-images.githubusercontent.com/1206968/78194184-5b005c00-7474-11ea-86e6-6359e91feb61.png)
