### ISSUE TITLE
how to compile wdi-simple.exe??

### ISSUE THREAD

**Issue by khushbooY** [pbatard/libwdi#182]
Sir I am not getting any link or idea how to compile wdi-simple.exe.
Actually i m trying to automate Zadig driver replacer for Win-USB and want to install Zadig driver while installing my application.there are some thing i don't get in ur wdi-simple.iss code could you please help!!

1. how to compile wdi-simple.exe what does it actually need win-usb driver's inf or sys ??
2. what does this part of code mean which file should be in these directories i didn't get??

```C
/*

Embed WinUSB driver files from the following WDK location
NB: You must also make sure the WDF_VER, COINSTALLER_DIR and X64_DIR
match your WinUSB redist directrories
*/
#ifndef WDK_DIR
#define WDK_DIR "C:/Program Files (x86)/Windows Kits/10"
#endif
/* WDK WDF coinstaller version */
#define WDF_VER 1011

/* CoInstaller subdirectory for WinUSB redist files ("winusb" or "wdf") */
#define COINSTALLER_DIR "wdf"

/* 64bit subdirectory for WinUSB redist files ("x64" or "amd64") */
#define X64_DIR "x64"
```

3. what things are required to create win.exe and use it??

I know my question is overwhelming but i seriouly didn't get it??

**Comment by pbatard** [comment]
https://github.com/pbatard/libwdi/wiki/Compiling-and-debugging-libwdi-or-Zadig

**Comment by pbatard** [comment]
I'm going to assume that the above did the trick and therefore close the issue.

**Comment by khushbooY** [comment]
sir i am getting this error while compilation.
![Capture](https://user-images.githubusercontent.com/48197133/81135997-da071980-8f77-11ea-94b2-b6d1981da1c9.PNG)

**Comment by khushbooY** [comment]
i tried the alternative which is given but still same error could you please help

**Comment by khushbooY** [comment]
![image](https://user-images.githubusercontent.com/48197133/81136233-9d87ed80-8f78-11ea-9442-5c2a91f57360.png)

**Comment by khushbooY** [comment]
After the relaunching of visual studio by different cerdentails i get this
![image](https://user-images.githubusercontent.com/48197133/81138099-687e9980-8f7e-11ea-8def-6061ca59bbc9.png)

**Comment by khushbooY** [comment]
Thank You sir It worked!!

**Comment by pbatard** [comment]
Great. I'm very happy to hear that!
