### ISSUE TITLE
cat_file_size and inf_file_size confusion?

### ISSUE THREAD

**Issue by spiro-trikaliotis** [pbatard/libwdi#186]
https://github.com/pbatard/libwdi/blob/d09916e83e8fba9f5abcbc9a42cf5f69726c28b0/libwdi/libwdi.c#L1293
I think the inf_file_size should be cat_file_size, right?
The inf_file_size is set some lines above, but cat_file_size is the current one.

**Comment by pbatard** [comment]
Thanks. I'll fix that when I have a chance.
