### ISSUE TITLE
Zadig 2.5 Replace a misappropriated webcam driver by mistake from me!

### ISSUE THREAD

**Issue by Hishine77** [pbatard/libwdi#187]
Hello, I am making this message because by default I replaced my webcam driver with winusb etc ... so I uninstall it but when I reinstall it does not work because even the path to install the origial driver has been erased. How to reset it please?

**Comment by pbatard** [comment]
https://github.com/pbatard/libwdi/wiki/FAQ#Help_Zadig_replaced_the_driver_for_the_wrong_device_How_do_I_restore_it

**Comment by Hishine77** [comment]
Thanks-you guys holala ...

**Comment by Hishine77** [comment]
my camera is integrated i must unplug it ?

**Comment by pbatard** [comment]
Try rebooting.

**Comment by Hishine77** [comment]
OK , I'm going to try ... :-(
