### ISSUE TITLE
Feature request: headless install

### ISSUE THREAD

**Issue by mlx-kva** [pbatard/libwdi#195]
Is there a way that zadig can be run without UI from the command line?

**Comment by pbatard** [comment]
No, but there is a sample called `wdi-simple` in the libwdi examples that is the equivalent of commandline Zadig:
https://github.com/pbatard/libwdi/tree/master/examples

You will have to compile it yourself, as I have no plans to provide any other executables besides Zadig. [This](https://github.com/pbatard/libwdi/wiki/Compiling-and-debugging-libwdi-or-Zadig) contains all the details you should need to compile `wdi-simple`.

**Comment by karelv** [comment]
cool, this sounds like it is what I am looking for! Thx, will try it soon...
