### ISSUE TITLE
I accidentally changed the settings of my headset while using your program. How can I fix?

### ISSUE THREAD

**Issue by bluefire418** [pbatard/libwdi#218]
I decided to use your program for my ps3 joystick. But when I entered the program, I accidentally changed the settings of my headset, how can I fix it? In the past, my headset was called speaker, but after doing something in zadig, it became USBFC1 - A and no longer works. I'm waiting for your answer. have a nice day
![Ekran Alıntısı](https://user-images.githubusercontent.com/76152924/123009676-d88bf100-d3c5-11eb-803b-5be98df441f1.PNG)

**Comment by pbatard** [comment]
https://github.com/pbatard/libwdi/wiki/FAQ#Help_Zadig_replaced_the_driver_for_the_wrong_device_How_do_I_restore_it
