### ISSUE TITLE
Signing user-mode (UMDF) drivers

### ISSUE THREAD

**Issue by JJTech0130** [pbatard/libwdi#239]
I can’t seem to find this in the MS docs, and other sources are conflicting: do user mode drivers need to be signed in order to run (like kernel mode drivers)?

**Comment by pbatard** [comment]
I'm afraid I have no idea, and this isn't the best place to ask such a question.

You may have better luck asking about this on https://community.osr.com/categories/ntdev.

**Comment by JJTech0130** [comment]
Thanks for the link! I hadn't seen that before!
