### ISSUE TITLE
Zadig: have problem when using zadig to install driver on Windows 11

### ISSUE THREAD

**Issue by triplearon** [pbatard/libwdi#242]
Seems the reason is certificate?
libwdi:debug [installer process] This version of Windows is refusing to trust the installed certificate.

> Zadig 2.7.765
Windows 11 Home China, 64-bit (Build 22509.1011)
ini file 'zadig.ini' not found in 'C:\Users\kokoro\Downloads' - default parameters will be used
default driver set to 'WinUSB'
1 device found.
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_1D50&PID_608C&REV_0001
libwdi:debug [wdi_create_list] Compatible ID: USB\Class_FF&SubClass_FF&Prot_FF
libwdi:debug [wdi_create_list] Driverless USB device (9): USB\VID_1D50&PID_608C\SIGROK_FX2_8CH
libwdi:debug [wdi_create_list] Device description: 'fx2lafw'
Using inf name: fx2lafw.inf
Successfully extracted driver files.
Installing driver. Please wait...
libwdi:info [extract_binaries] Successfully extracted driver files to 'C:\Users\kokoro\usb_driver'
libwdi:info [wdi_prepare_driver] Successfully created 'C:\Users\kokoro\usb_driver\fx2lafw.inf'
libwdi:info [wdi_prepare_driver] Creating and self-signing a .cat file...
libwdi:info [wdi_prepare_driver] Test signing is: Disabled
libwdi:debug [AddFileHash] 'wdfcoinstaller01011.dll': PE type
libwdi:info [ScanDirAndHash] added hash for 'C:\Users\kokoro\usb_driver\amd64\wdfcoinstaller01011.dll'
libwdi:debug [AddFileHash] 'winusbcoinstaller2.dll': PE type
libwdi:info [ScanDirAndHash] added hash for 'C:\Users\kokoro\usb_driver\amd64\winusbcoinstaller2.dll'
libwdi:debug [AddFileHash] 'fx2lafw.inf': INF type
libwdi:info [ScanDirAndHash] added hash for 'C:\Users\kokoro\usb_driver\fx2lafw.inf'
libwdi:debug [AddFileHash] 'wdfcoinstaller01011.dll': PE type
libwdi:info [ScanDirAndHash] added hash for 'C:\Users\kokoro\usb_driver\x86\wdfcoinstaller01011.dll'
libwdi:debug [AddFileHash] 'winusbcoinstaller2.dll': PE type
libwdi:info [ScanDirAndHash] added hash for 'C:\Users\kokoro\usb_driver\x86\winusbcoinstaller2.dll'
libwdi:info [CreateCat] Successfully created file 'C:\Users\kokoro\usb_driver\fx2lafw.cat'
libwdi:info [RemoveCertFromStore] Deleted existing certificate 'CN=USB\VID_1D50&PID_608C (libwdi autogenerated)' from 'Root' store
libwdi:info [RemoveCertFromStore] Deleted existing certificate 'CN=USB\VID_1D50&PID_608C (libwdi autogenerated)' from 'TrustedPublisher' store
libwdi:debug [CreateSelfSignedCert] Set Enhanced Key Usage, URL and CPS
libwdi:debug [CreateSelfSignedCert] Created new key container
libwdi:debug [CreateSelfSignedCert] Generated new keypair...
libwdi:info [CreateSelfSignedCert] Created new self-signed certificate 'CN=USB\VID_1D50&PID_608C (libwdi autogenerated)'
libwdi:debug [SelfSignFile] Successfully created certificate 'CN=USB\VID_1D50&PID_608C (libwdi autogenerated)'
libwdi:info [SelfSignFile] Added certificate 'CN=USB\VID_1D50&PID_608C (libwdi autogenerated)' to 'Root' and 'TrustedPublisher' stores
libwdi:info [SelfSignFile] Successfully signed file 'C:\Users\kokoro\usb_driver\fx2lafw.cat'
libwdi:info [SelfSignFile] Successfully deleted private key
libwdi:debug [wdi_install_driver] Using progress bar mode
libwdi:debug [installer process] got parameter fx2lafw.inf
libwdi:debug [process_message] Got request for device_id
libwdi:debug [installer process] got device_id: 'USB\VID_1D50&PID_608C\SIGROK_FX2_8CH'
libwdi:debug [process_message] Got request for hardware_id
libwdi:debug [installer process] got hardware_id: 'USB\VID_1D50&PID_608C&REV_0001'
libwdi:debug [installer process] got user_sid: 'S-1-5-21-3255351301-14170022-3940030004-1001'
libwdi:debug [installer process] using syslog 'C:\WINDOWS\inf\setupapi.dev.log'
libwdi:debug [installer process] syslog reader thread started
libwdi:debug [installer process] successfully disabled the system restore point creation setting
libwdi:debug [process_message] Switching timeout to infinite
libwdi:debug [installer process] Installing driver for USB\VID_1D50&PID_608C&REV_0001 - please wait...
libwdi:debug [syslog] <Garbled data>
libwdi:debug [syslog] s) - USB\VID_1D50&PID_608C&REV_0001]
libwdi:debug [syslog] >>>  Section start 2021/12/23 22:40:47.034
libwdi:debug [syslog]       cmd: "C:\Users\kokoro\usb_driver\installer_x64.exe" "fx2lafw.inf"
libwdi:debug [syslog] vice Install (UpdateDriverForPlugAndPlayDevices) - USB\VID_1D50&PID_608C&REV_0001]
libwdi:debug [syslog] >>>  Section start 2021/12/23 22:40:47.034
libwdi:debug [syslog]       cmd: "C:\Users\kokoro\usb_driver\installer_x64.exe" "fx2lafw.inf"
libwdi:debug [syslog] <Garbled data>
libwdi:debug [syslog]       cmd: "C:\Users\kokoro\usb_driver\installer_x64.exe" "fx2lafw.inf"
libwdi:debug [syslog] S]
libwdi:debug [syslog] >>>  [Device Install (UpdateDriverForPlugAndPlayDevices) - USB\VID_1D50&PID_608C&REV_0001]
libwdi:debug [syslog] >>>  Section start 2021/12/23 22:36:06.261
libwdi:debug [syslog]       cmd: "C:\Users\kokoro\usb_driver\installer_x64.exe" "fx2lafw.inf"
libwdi:debug [syslog] _Yangra,*
libwdi:debug [syslog]      dvi:           Install Device: Configuring device completed. 11:16:35.513
libwdi:debug [syslog]      dvi:           Device Status: 0x01802000
libwdi:debug [syslog]      dvi:           {Restarting Devices} 11:16:35.513
libwdi:debug [syslog]      dvi:                Start: SWD\DRIVERENUM\CUI&4&BEA98B6&0
libwdi:debug [syslog]      dvi:           {Restarting Devices exit} 11:16:35.518
libwdi:debug [syslog]      dvi:      {Configure Device - exit(0x00000000)} 11:16:35.518
libwdi:debug [syslog]      dvi: {Core Device Install - exit(0x00000000)} 11:16:35.518
libwdi:debug [syslog] <<<  Section end 2021/12/23 11:16:35.538
libwdi:debug [syslog] <<<  [Exit status: SUCCESS]
libwdi:debug [syslog] >>>  [Device Install (UpdateDriverForPlugAndPlayDevices) - USB\VID_1D50&PID_608C&REV_0001]
libwdi:debug [syslog] >>>  Section start 2021/12/23 22:36:06.261
libwdi:debug [syslog]       cmd: "C:\Users\kokoro\usb_driver\installer_x64.exe" "fx2lafw.inf"
libwdi:debug [syslog] Device: Configuring device. 11:16:35.508
libwdi:debug [syslog]      dvi:                Configuration: oem115.inf:SWC\100.9876_VEN8086_GFXUI_App_Yangra,*
libwdi:debug [syslog]      dvi:           Install Device: Configuring device completed. 11:16:35.513
libwdi:debug [syslog]      dvi:           Device Status: 0x01802000
libwdi:debug [syslog]      dvi:           {Restarting Devices} 11:16:35.513
libwdi:debug [syslog]      dvi:                Start: SWD\DRIVERENUM\CUI&4&BEA98B6&0
libwdi:debug [syslog]      dvi:           {Restarting Devices exit} 11:16:35.518
libwdi:debug [syslog]      dvi:      {Configure Device - exit(0x00000000)} 11:16:35.518
libwdi:debug [syslog]      dvi: {Core Device Install - exit(0x00000000)} 11:16:35.518
libwdi:debug [syslog] <<<  Section end 2021/12/23 11:16:35.538
libwdi:debug [syslog] <<<  [Exit status: SUCCESS]
libwdi:debug [syslog] >>>  [Device Install (UpdateDriverForPlugAndPlayDevices) - USB\VID_1D50&PID_608C&REV_0001]
libwdi:debug [syslog] >>>  Section start 2021/12/23 22:36:06.261
libwdi:debug [syslog]       cmd: "C:\Users\kokoro\usb_driver\installer_x64.exe" "fx2lafw.inf"
libwdi:debug [syslog] s driver.
libwdi:debug [syslog]      dvi:           Install Device: Configuring device. 11:16:35.508
libwdi:debug [syslog]      dvi:                Configuration: oem115.inf:SWC\100.9876_VEN8086_GFXUI_App_Yangra,*
libwdi:debug [syslog]      dvi:           Install Device: Configuring device completed. 11:16:35.513
libwdi:debug [syslog]      dvi:           Device Status: 0x01802000
libwdi:debug [syslog]      dvi:           {Restarting Devices} 11:16:35.513
libwdi:debug [syslog]      dvi:                Start: SWD\DRIVERENUM\CUI&4&BEA98B6&0
libwdi:debug [syslog]      dvi:           {Restarting Devices exit} 11:16:35.518
libwdi:debug [syslog]      dvi:      {Configure Device - exit(0x00000000)} 11:16:35.518
libwdi:debug [syslog]      dvi: {Core Device Install - exit(0x00000000)} 11:16:35.518
libwdi:debug [syslog] <<<  Section end 2021/12/23 11:16:35.538
libwdi:debug [syslog] <<<  [Exit status: SUCCESS]
libwdi:debug [syslog] >>>  [Device Install (UpdateDriverForPlugAndPlayDevices) - USB\VID_1D50&PID_608C&REV_0001]
libwdi:debug [syslog] >>>  Section start 2021/12/23 22:36:06.261
libwdi:debug [syslog]       cmd: "C:\Users\kokoro\usb_driver\installer_x64.exe" "fx2lafw.inf"
libwdi:debug [syslog] <Garbled data>
libwdi:debug [syslog]      inf:                          Service Name  = <none>
libwdi:debug [syslog]      inf:                          Config Flags  = 0x00000000
libwdi:debug [syslog]      inf:                     {Configure Driver Configuration: exit(0x00000000)}
libwdi:debug [syslog]      inf:                {Configure Driver: exit(0x00000000)}
libwdi:debug [syslog]      flq:                {FILE_QUEUE_COMMIT} 11:16:35.348
libwdi:debug [syslog]      flq:                {FILE_QUEUE_COMMIT - exit(0x00000000)} 11:16:35.353
libwdi:debug [syslog]      inf:                Restarted service 'igfxCUIService2.0.0.0'.
libwdi:debug [syslog]      dvi:                Existing files modified, may need to restart related services.
libwdi:debug [syslog]      sto:           {Configure Driver Package: exit(0x00000bc3)}
libwdi:debug [syslog]      dvi:           Restart required for any devices using this driver.
libwdi:debug [syslog]      dvi:           Install Device: Configuring device. 11:16:35.508
libwdi:debug [syslog]      dvi:                Configuration: oem115.inf:SWC\100.9876_VEN8086_GFXUI_App_Yangra,*
libwdi:debug [syslog]      dvi:           Install Device: Configuring device completed. 11:16:35.513
libwdi:debug [syslog]      dvi:           Device Status: 0x01802000
libwdi:debug [syslog]      dvi:           {Restarting Devices} 11:16:35.513
libwdi:debug [syslog]      dvi:                Start: SWD\DRIVERENUM\CUI&4&BEA98B6&0
libwdi:debug [syslog]      dvi:           {Restarting Devices exit} 11:16:35.518
libwdi:debug [syslog]      dvi:      {Configure Device - exit(0x00000000)} 11:16:35.518
libwdi:debug [syslog]      dvi: {Core Device Install - exit(0x00000000)} 11:16:35.518
libwdi:debug [syslog] <<<  Section end 2021/12/23 11:16:35.538
libwdi:debug [syslog] <<<  [Exit status: SUCCESS]
libwdi:debug [syslog] >>>  [Device Install (UpdateDriverForPlugAndPlayDevices) - USB\VID_1D50&PID_608C&REV_0001]
libwdi:debug [syslog] >>>  Section start 2021/12/23 22:36:06.261
libwdi:debug [syslog]       cmd: "C:\Users\kokoro\usb_driver\installer_x64.exe" "fx2lafw.inf"
libwdi:debug [syslog] <Garbled data>
libwdi:debug [syslog]      dvi:           Install Device: Configuring device completed. 11:16:35.513
libwdi:debug [syslog]      dvi:           Device Status: 0x01802000
libwdi:debug [syslog]      dvi:           {Restarting Devices} 11:16:35.513
libwdi:debug [syslog]      dvi:                Start: SWD\DRIVERENUM\CUI&4&BEA98B6&0
libwdi:debug [syslog]      dvi:           {Restarting Devices exit} 11:16:35.518
libwdi:debug [syslog]      dvi:      {Configure Device - exit(0x00000000)} 11:16:35.518
libwdi:debug [syslog]      dvi: {Core Device Install - exit(0x00000000)} 11:16:35.518
libwdi:debug [syslog] <<<  Section end 2021/12/23 11:16:35.538
libwdi:debug [syslog] <<<  [Exit status: SUCCESS]
libwdi:debug [syslog] >>>  [Device Install (UpdateDriverForPlugAndPlayDevices) - USB\VID_1D50&PID_608C&REV_0001]
libwdi:debug [syslog] >>>  Section start 2021/12/23 22:36:06.261
libwdi:debug [syslog]       cmd: "C:\Users\kokoro\usb_driver\installer_x64.exe" "fx2lafw.inf"
libwdi:debug [syslog]    inf:                     Section Name = Igdlh_CUI_App_Component_Install_Yangra
libwdi:debug [syslog]      inf:                     {Add Service: igfxCUIService2.0.0.0}
libwdi:debug [syslog]      inf:                          Start Type    = 2
libwdi:debug [syslog]      inf:                          Service Type  = 16
libwdi:debug [syslog]      inf:                          Error Control = 1
libwdi:debug [syslog]      inf:                          Image Path    = %SystemRoot%\System32\DriverStore\FileRepository\cui_dch.inf_amd64_744bdf6288685506\igfxCUIServiceN.exe
libwdi:debug [syslog]      inf:                          Display Name  = Intel(R) HD Graphics Control Panel Service
libwdi:debug [syslog]      inf:                          Description   = Service for Intel(R) HD Graphics Control Panel
libwdi:debug [syslog]      inf:                          Group         = ProfSvc_Group
libwdi:debug [syslog]      inf:                          Dependencies  = SENS
libwdi:debug [syslog]      inf:                          Updated service 'igfxCUIService2.0.0.0'.
libwdi:debug [syslog]      inf:                          Service image path changed. Restart required for any devices using this service.
libwdi:debug [syslog] !    idb:                          Last driver package 'cui_dch.inf_amd64_e5ef6244bae44b2d' using service 'igfxCUIService2.0.0.0' needs reconfiguration.
libwdi:debug [syslog]      inf:                     {Add Service: exit(0x00000000)}
libwdi:debug [syslog]      inf:                     Hardware Id  = SWC\100.9876_VEN8086_GFXUI_App_Yangra
libwdi:debug [syslog]      inf:                     {Configure Driver Configuration: Igdlh_CUI_App_Component_Install_Yangra}
libwdi:debug [syslog]      inf:                          Service Name  = <none>
libwdi:debug [syslog]      inf:                          Config Flags  = 0x00000000
libwdi:debug [syslog]      inf:                     {Configure Driver Configuration: exit(0x00000000)}
libwdi:debug [syslog]      inf:                {Configure Driver: exit(0x00000000)}
libwdi:debug [syslog]      flq:                {FILE_QUEUE_COMMIT} 11:16:35.348
libwdi:debug [syslog]      flq:                {FILE_QUEUE_COMMIT - exit(0x00000000)} 11:16:35.353
libwdi:debug [syslog]      inf:                Restarted service 'igfxCUIService2.0.0.0'.
libwdi:debug [syslog]      dvi:                Existing files modified, may need to restart related services.
libwdi:debug [syslog]      sto:           {Configure Driver Package: exit(0x00000bc3)}
libwdi:debug [syslog]      dvi:           Restart required for any devices using this driver.
libwdi:debug [syslog]      dvi:           Install Device: Configuring device. 11:16:35.508
libwdi:debug [syslog]      dvi:                Configuration: oem115.inf:SWC\100.9876_VEN8086_GFXUI_App_Yangra,*
libwdi:debug [syslog]      dvi:           Install Device: Configuring device completed. 11:16:35.513
libwdi:debug [syslog]      dvi:           Device Status: 0x01802000
libwdi:debug [syslog]      dvi:           {Restarting Devices} 11:16:35.513
libwdi:debug [syslog]      dvi:                Start: SWD\DRIVERENUM\CUI&4&BEA98B6&0
libwdi:debug [syslog]      dvi:           {Restarting Devices exit} 11:16:35.518
libwdi:debug [syslog]      dvi:      {Configure Device - exit(0x00000000)} 11:16:35.518
libwdi:debug [syslog]      dvi: {Core Device Install - exit(0x00000000)} 11:16:35.518
libwdi:debug [syslog] <<<  Section end 2021/12/23 11:16:35.538
libwdi:debug [syslog] <<<  [Exit status: SUCCESS]
libwdi:debug [syslog] >>>  [Device Install (UpdateDriverForPlugAndPlayDevices) - USB\VID_1D50&PID_608C&REV_0001]
libwdi:debug [syslog] >>>  Section start 2021/12/23 22:36:06.261
libwdi:debug [syslog]       cmd: "C:\Users\kokoro\usb_driver\installer_x64.exe" "fx2lafw.inf"
libwdi:debug [syslog] tall (UpdateDriverForPlugAndPlayDevices) - USB\VID_1D50&PID_608C&REV_0001]
libwdi:debug [syslog] >>>  Section start 2021/12/23 22:36:06.261
libwdi:debug [syslog]       cmd: "C:\Users\kokoro\usb_driver\installer_x64.exe" "fx2lafw.inf"
libwdi:debug [syslog] tarting Devices exit} 11:16:35.518
libwdi:debug [syslog]      dvi:      {Configure Device - exit(0x00000000)} 11:16:35.518
libwdi:debug [syslog]      dvi: {Core Device Install - exit(0x00000000)} 11:16:35.518
libwdi:debug [syslog] <<<  Section end 2021/12/23 11:16:35.538
libwdi:debug [syslog] <<<  [Exit status: SUCCESS]
libwdi:debug [syslog] >>>  [Device Install (UpdateDriverForPlugAndPlayDevices) - USB\VID_1D50&PID_608C&REV_0001]
libwdi:debug [syslog] >>>  Section start 2021/12/23 22:36:06.261
libwdi:debug [syslog]       cmd: "C:\Users\kokoro\usb_driver\installer_x64.exe" "fx2lafw.inf"
libwdi:debug [syslog] start 2021/12/23 22:36:06.261
libwdi:debug [syslog]       cmd: "C:\Users\kokoro\usb_driver\installer_x64.exe" "fx2lafw.inf"
libwdi:debug [process_message] Switching timeout back to finite
libwdi:debug [installer process] This version of Windows is refusing to trust the installed certificate.
libwdi:debug [process_message] Installer process completed
Driver Installation: FAILED (Operation not supported or not implemented)
1 device found.
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_1D50&PID_608C&REV_0001
libwdi:debug [wdi_create_list] Compatible ID: USB\Class_FF&SubClass_FF&Prot_FF
libwdi:debug [wdi_create_list] Driverless USB device (9): USB\VID_1D50&PID_608C\SIGROK_FX2_8CH
libwdi:debug [wdi_create_list] Device description: 'fx2lafw'
1 device found.
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_1D50&PID_608C&REV_0001
libwdi:debug [wdi_create_list] Compatible ID: USB\Class_FF&SubClass_FF&Prot_FF
libwdi:debug [wdi_create_list] Driverless USB device (9): USB\VID_1D50&PID_608C\SIGROK_FX2_8CH
libwdi:debug [wdi_create_list] Device description: 'fx2lafw'
1 device found.
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_1D50&PID_608C&REV_0001
libwdi:debug [wdi_create_list] Compatible ID: USB\Class_FF&SubClass_FF&Prot_FF
libwdi:debug [wdi_create_list] Driverless USB device (9): USB\VID_1D50&PID_608C\SIGROK_FX2_8CH
libwdi:debug [wdi_create_list] Device description: 'fx2lafw'

**Comment by pbatard** [comment]
> `Build 22509.1011`

This looks like a pre-release/insider build, which we don't support. A current non insider release of Windows 11 should be `Build 22000.376`.

This is a know issue with the insider/pre-release builds of Windows 11, where Microsoft appears to be testing more stringent driver installation restrictions. And since we are using self-generated certificate for driver installation, it's not a matter of Zadig needing to use a "better" certificate, because there's nothing better we can use here.

See https://community.osr.com/discussion/293115/windows-11-and-alternative-driver-installation-method-in-libwdi for more details.

As long as this issue only manifests itself with Insider builds, I'm not planning to look into it further.

And even if it happens with release, it doesn't look like there's much I'll be able to do about it, since it looks like Microsoft has decided to renegue on what they publicly stated [here](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/trusted-publishers-certificate-store) in that, despite what they are documenting, Windows 11 may no longer trust certificates installed under Trusted Publishers for driver installation...
