### ISSUE TITLE
How do I undo?

### ISSUE THREAD

**Issue by afroJezuz** [pbatard/libwdi#245]
I have no Previous Versions to reinstate.
It was an HidUsb before converting to WinUSB, which will not correct itself back to HidUsb when I uninstall the driver and plug the device back in.

Is this C\Users\User\usb_Driver folder the cause?
Did Zandig change the device's auto-installing driver?

I just want to return to the HidUsb version which is the initial driver installed when I plugged in the device.

**Comment by pbatard** [comment]
https://github.com/pbatard/libwdi/wiki/FAQ#Help_Zadig_replaced_the_driver_for_the_wrong_device_How_do_I_restore_it
