### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Toxicide** [pbatard/libwdi#249]
I tried to change the port on my mouse and now its not working

**Comment by pbatard** [comment]
1. You don't change the port of a USB device with Zadig or libwdi. Zadig can't change the port. So, whatever you thought Zadig/libwdi were going to help you with was very very wrong.
2. https://github.com/pbatard/libwdi/wiki/FAQ#Help_Zadig_replaced_the_driver_for_the_wrong_device_How_do_I_restore_it
