### ISSUE TITLE
libusb0 x86

### ISSUE THREAD

**Issue by Rinat84** [pbatard/libwdi#250]
Error when using libusb0.dll.
In the study, I found out that there is no export table in the files **_\amd64\libusb0_x86.dll_** and **_\x86\libusb0.dll_**.
Единственная правильная dll это **_\x86\libusb0_x86.dll_**.

**Comment by pbatard** [comment]
That's not a libwdi problem.

The files are provided by the [libusb-win32 project](https://sourceforge.net/projects/libusb-win32/) and aren't generated by libwdi. We also don't modify them from the published version. The libraries we install through libwdi are for the sole purpose of enabling the `libusb0.sys` driver to work when used with [libusb](https://libusb.info/) and libwdi expects you to work with a libusb 1.0 (not libusb-win32) based application.

Therefore, if you have issues using the libusb-win32 DLLs, you will have to provide your own DLLs or report that problem to the libusb-win32 mailing list (and, if you do so, please, provide more details about what it is you are trying to accomplish exactly and how).
