### ISSUE TITLE
The mistake about Microsoft Extended Properties Feature Descriptor example 

### ISSUE THREAD

**Issue by MicroGrit** [pbatard/libwdi#252]
In table 4 of the wiki page,  the NUL-terminated Unicode String (LE) of Property name “DeviceInterfaceGUID” may be mistake.
The unicode of "DeviceInterfaceGUID" is ['0x44', '0x65', '0x76', '0x69', '0x63', '0x65', '0x49', '0x6e', '0x74', '0x65', '0x72', '0x66', '0x61', '0x63', '0x65', '0x47', '0x55', '0x49', '0x44']. 
So, the example of NUL-terminated Unicode String (LE) should as follows:

|0x44, 0x00, 0x65, 0x00,<br>(...)<br><font color="red">0x44</font> 0x00, 0x00, 0x00 | NUL-terminated Unicode String (LE) | Property name"DeviceInterfaceGUID"|
|:-:| :-: |:-:|

Original example is:

|0x44, 0x00, 0x65, 0x00,<br>(...)<br><font color="red">0x74</font> 0x00, 0x00, 0x00 | NUL-terminated Unicode String (LE) | Property name"DeviceInterfaceGUID"|
|:-:| :-: |:-:|

<font color="red">**The original 0x74 should be modified to 0x44.**</font>

Ambiguous examples may lead to misunderstandings for developers.  If what I describe makes sense, please update the wiki page. In addition, If my above description is wrong, please let me know why.

Looking forward to your reply! 
Thanks!

**Comment by pbatard** [comment]
Yeah, that was a typo. This is fixed now. Thanks for reporting it.
