### ISSUE TITLE
Zadig: The driver installation is failed

### ISSUE THREAD

**Issue by ChekistNSK** [pbatard/libwdi#258]
>>>  [Device Install (UpdateDriverForPlugAndPlayDevices) - USB\VID_1F3A&PID_EFE8&REV_02;3]
>>>  Section start 2022/04/17 17:04:25.173
      cmd: "C:\Users\Evgeny\usb_driver\installer_x64.exe" "NES_Mini.inf"
<ins>

>>>  [Device Installation Restrictions Policy Check]
>>>  Section start 2022/04/17 17:04:31.555
<ins>

**Comment by pbatard** [comment]
Please provide the full log from Zadig. Noone will be able to help you without a full log.

To access the log in Zadig: _Options_ &rarr; _Advanced Mode_

**Comment by ChekistNSK** [comment]
The problem is solved.
It was necessary to run the program with administrator rights
