### ISSUE TITLE
Does libwdi support software-first installation?

### ISSUE THREAD

**Issue by YueLu0116** [pbatard/libwdi#259]
In my project, I want to prepare the drivers for certain devices first, so when the devices are plugged in, they can work immediately. In MSDN, this way is called [software-first installation](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/software-first-installation). Does libwdi support this?

**Comment by pbatard** [comment]
It does.

For instance, in Zadig you can select `Device` &rarr; `Create New Device`. And there are options to pass a VID and a PID in wdi-simple too.
