### ISSUE TITLE
 my zadig does not show any device

### ISSUE THREAD

**Issue by jonandr001** [pbatard/libwdi#276]
<img width="467" alt="image" src="https://user-images.githubusercontent.com/114286306/192166055-618df2e2-28a7-4b44-aa31-308766ae345e.png">
I'm trying to use zadig to install the ps3 camera on my pc but no device appears

**Comment by pbatard** [comment]
_Options_ &rarr; _List All Devices_

Be mindful however that you will be __REPLACING__ the existing driver, therefore preventing applications that were able to use your camera from accessing it.
