### ISSUE TITLE
Option for install as non-removable

### ISSUE THREAD

**Issue by yw4z** [pbatard/libwdi#278]
Hi thanks for your efforts on this

i changed my corsair h115i driver to winUSB with this tool
but windows shows device as a removable

not sure is this possible but it would be great if possible to show as non removable

**Comment by pbatard** [comment]
removable vs non removable is a hardware property (i.e. it is provided by the USB firmware of your device, __NOT__ by the PC host).

So what you are asking is not possible.

**Comment by yw4z** [comment]
wow fastest reply ever :)

i tried from registry on  HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Enum\USB\VID_1B1C&PID_0C13\7289_2.0 > capabilities
it will gone after restart, also not hiding safely remove icon, just hides device name on that

there is no policy option on Device manager > device properties

device is non-removable on original drivers

let me know if another way

thanks
