### ISSUE TITLE
why MUTEX_START added?

### ISSUE THREAD

**Issue by jdzyzh** [pbatard/libwdi#284]
I do not understand why MUTEX_START added in wdi_create_list and etc ? 
May I remove MUTEX_START ?  As I need wdi to check android mobilephone plug in, while there is another checking ios usb devcie plug in by exe includes wdi running. While conflict produced by that.

**Comment by pbatard** [comment]
It's an Opne Source project, so you're free to clone, modify and compile the code in whichever way you want.

I will however **not** remove the mutex from the code I maintain.
