### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Joaofodinha23** [pbatard/libwdi#287]
I ended up adding the driver to the wrong device, is there any way to reinstall the old driver back (example: I changed the hidusb of a keyboard for winusb and the keyboard now does not work as it should)

**Comment by pbatard** [comment]
https://github.com/pbatard/libwdi/wiki/FAQ#user-content-Help_Zadig_replaced_the_driver_for_the_wrong_device_How_do_I_restore_it

Hope this helps.

**Comment by Joaofodinha23** [comment]
Is there any way to add the "hidusb" driver for zadig to replace?

**Comment by pbatard** [comment]
The HIDUSB driver comes from Windows, and gets installed __automatically__ for HID USB devices. There's no need to any external utility to "install" that driver. It simply gets installed or reinstalled by Windows (as long as you don't __forcefully__ replace it with another driver, in which case you must make sure that that other driver is fully uninstalled first).

**Comment by Joaofodinha23** [comment]
oh, thank you. It worked. yesterday I was trying to uninstall libusb from my keyboard and it didn't come out at all and today it worked and it's back to normal
