### ISSUE TITLE
I am using the win10 x64 system. I want to know if this is a mobile device problem or a computer problem.

### ISSUE THREAD

**Issue by 5tiaowu** [pbatard/libwdi#295]
Unable to install the driver device is Mi 5

![image](https://github.com/pbatard/libwdi/assets/108533707/078a4dbd-f106-428f-be06-23896f2d4569)

**Comment by mcuee** [comment]
You have to post the full debug log (save the debug log and then post the full contents) and not just the screenshot.

**Comment by pbatard** [comment]
No update &rarr; Closed.
