### ISSUE TITLE
Zadig driver installation not persistent?

### ISSUE THREAD

**Issue by patzf** [pbatard/libwdi#303]
Not sure if that is a zadig issue. Using the dfu-util to flash the binary code to a microcontroller through libusb on Windows 10. For this to work, the DFU device has to be recognised as a WINUSB device (instead of libusb0). I use Zadig to change the driver assigned to the device from libusb to WINUSB. That works and the dfu-util can talk through WINUSB once(!). After unplugging and replugging the USB device oder doing  power cycle, the old (libusb0) driver is again assigned. How can I make the driver installation "persistent"?

**Comment by pbatard** [comment]
That's not a Zadig issue. You need to make sure that the libusb0 driver is fully uninstalled before you install the WinUSB one. To uninstall the libusb0 driver, you should make sure your device has been plugged into every USB port it's ever been plugged into, and select uninstall driver every time. Or in Device Manager, you can select _Show hidden devices_ in the _View_ menu and make sure you uninstall the libusb0 driver everywhere.

As this is not a Zadig problem, I will close this issue.
