### ISSUE TITLE
Driving Force GT buttons not working in GT5, only D-pad

### ISSUE THREAD

**Issue by sulakk2023** [pbatard/libwdi#305]
Installed for Gran Turismo 5 on RPC3 to play with Logitech Driving Force GT
D-pad on the wheel works in game but other buttons don't. I had Xbox360 pad working through XInput before installing Zadig, after that buttons on the joystick also stopped working.
When I disconnect the Logitech Driving Force GT wheel Xbox360 pad still has buttons not working.  But analog joysticks moving register in the RPC3 pad config menu, buttons also register. But in the game Xbox360 pad buttons stopped working. Device Manager shows device as Driving Force GT. I had official Logitech driver installed before all that.
After I have deleted RPC3 and installed everything from scratch Xbox360 pad started working as normal.

Windows 10, Intel 10100F, 16GB RAM, AMD RX6600

**Comment by pbatard** [comment]
I'm afraid that your issue has nothing to do with this project.

libwdi/Zadig installs a __generic__ USB driver. The driver has absolutely zero knowledge of specifics related to this or that device. It is therefore up to the applications using that driver to access the device to sort out the actual device features.
