### ISSUE TITLE
Zadig 2.8 crashing during install WinUSB

### ISSUE THREAD

**Issue by lordrak007** [pbatard/libwdi#312]
I have selected device "Bulk-In, Interface (Interface 0)", press install but Zadig crash every time, so i cant catch install log.
I event log i found only error 1000 and 1001
OS Windows 11

```
Chybný blok 1542824719622668933, typ 1
Název události: APPCRASH
Reakce: Není k dispozici.
ID souboru CAB: 0

Podpis problému:
P1: Zadig-2.8.exe
P2: 2.8.782.0
P3: 63ff91c7
P4: Zadig-2.8.exe
P5: 2.8.782.0
P6: 63ff91c7
P7: c0000005
P8: 00028511
P9: 
P10: 
```

Zadig created cat file and inf file. I havce also find installed certificate in both locations.
How to solve driver installation? Manual selection formdevice manager end with error (without any description)
Thank you

**Comment by pbatard** [comment]
Please install DebugView from https://learn.microsoft.com/en-us/sysinternals/downloads/debugview.
Run the executable that matches your platform (most likely `dbgview64.exe`).
Then run Zadig and perform the operation that crashes. You will see the output from Zadig in DebugView.
Please post the full output here.

**Comment by lordrak007** [comment]
Hi, i run debugview, then zadig
here is result
00000001	0.00000000	[25988] [Init] TransitSharedMemName: Global\6FC1E623EB9152	
00000002	0.00004400	[25988] [Init] TransitCtrlMutexName: Global\5BA3732E71	
00000003	0.00006990	[25988] [Init] TransitFullEventName: Global\86495ED975	
00000004	0.00009300	[25988] [Init] TransitFullEventReplyName: Global\0369ABCD8D	
00000005	0.38588229	[24180] [Init] TransitSharedMemName: Global\6FC1E623EB9152	
00000006	0.38671660	[24180] [Init] TransitCtrlMutexName: Global\5BA3732E71	
00000007	0.38827670	[24180] [Init] TransitFullEventName: Global\86495ED975	
00000008	0.39030561	[24180] [Init] TransitFullEventReplyName: Global\0369ABCD8D	
00000009	2.67121959	[17316] [Init] TransitSharedMemName: Global\6FC1E623EB9152	
00000010	2.67123818	[17316] [Init] TransitCtrlMutexName: Global\5BA3732E71	
00000011	2.67133832	[17316] [Init] TransitFullEventName: Global\86495ED975	
00000012	2.67138314	[17316] [Init] TransitFullEventReplyName: Global\0369ABCD8D	
00000013	3.38836002	[17316] Zadig 2.8.782 	
00000014	3.39129162	[17316] Windows 11 Enterprise, 64-bit (Build 22621.3007) 	
00000015	3.39250565	[17316] ini file 'zadig.ini' not found in 'D:\_docasne\smaz\sdrpp_windows_x64\Drivers-RTL-SRD-x64' - default parameters will be used 	
00000016	3.39352918	[17316] default driver set to 'WinUSB' 	
00000017	3.75188231	[17316] 1 device found. 	
00000018	3.81579876	[17316] libwdi:debug [wdi_create_list] Hardware ID: USB\VID_0BDA&PID_2838&REV_0100&MI_00 	
00000019	3.82119513	[17316] libwdi:debug [wdi_create_list] Compatible ID: USB\COMPAT_VID_0bda&Class_ff&SubClass_ff&Prot_ff 	
00000020	3.82340765	[17316] libwdi:debug [wdi_create_list] Driverless USB device (1): USB\VID_0BDA&PID_2838&MI_00\6&38A180A5&0&0000 	
00000021	3.82437444	[17316] libwdi:debug [wdi_create_list] Device description: 'Bulk-In, Interface (Interface 0)' 	
00000022	7.36095142	[10220] [0130/201329.159:ERROR:filesystem_win.cc(128)] GetFileAttributes C:\Users\marek\AppData\Local\Google\Chrome\User Data\Crashpad\attachments\049fb104-1bae-45cf-8f31-83582fdf6193: Systém nemůže nalézt uvedený soubor. (0x2)	
00000023	7.36134815	[10220] [0130/201329.159:ERROR:filesystem_win.cc(128)] GetFileAttributes C:\Users\marek\AppData\Local\Google\Chrome\User Data\Crashpad\attachments\930fee1f-f8e8-4aee-969a-2e43518ba192: Systém nemůže nalézt uvedený soubor. (0x2)	
00000024	7.36172628	[10220] [0130/201329.159:ERROR:filesystem_win.cc(128)] GetFileAttributes C:\Users\marek\AppData\Local\Google\Chrome\User Data\Crashpad\attachments\ac0d268c-e652-406f-9bed-a5fb2c6c2844: Systém nemůže nalézt uvedený soubor. (0x2)	
00000025	7.36211061	[10220] [0130/201329.159:ERROR:filesystem_win.cc(128)] GetFileAttributes C:\Users\marek\AppData\Local\Google\Chrome\User Data\Crashpad\attachments\cafeb57f-0834-4fc2-bc12-43f0b3dceb3e: Systém nemůže nalézt uvedený soubor. (0x2)	
00000026	7.36249590	[10220] [0130/201329.159:ERROR:filesystem_win.cc(128)] GetFileAttributes C:\Users\marek\AppData\Local\Google\Chrome\User Data\Crashpad\attachments\7b99f600-ceae-4a01-9407-efd5c2ca2270: Systém nemůže nalézt uvedený soubor. (0x2)	
00000027	7.36289263	[10220] [0130/201329.159:ERROR:filesystem_win.cc(128)] GetFileAttributes C:\Users\marek\AppData\Local\Google\Chrome\User Data\Crashpad\attachments\a7ad54a5-5ee0-4306-a4e8-131345879edc: Systém nemůže nalézt uvedený soubor. (0x2)	
00000028	11.14993858	[22004] Suspending	
00000029	51.06132126	[17316] Using inf name: Bulk-In_Interface_(Interface_0).inf 	
00000030	55.12146378	[22004] Suspending	
00000031	141.78814697	[8336] [Init] TransitSharedMemName: Global\6FC1E623EB9152	
00000032	141.79203796	[8336] [Init] TransitCtrlMutexName: Global\5BA3732E71	
00000033	141.79446411	[8336] [Init] TransitFullEventName: Global\86495ED975	
00000034	141.80104065	[8336] [Init] TransitFullEventReplyName: Global\0369ABCD8D

**Comment by lordrak007** [comment]
Hi, can i do something more?

**Comment by pbatard** [comment]
Sorry for the late reply. I'm afraid that, since the crash seems very specific to your environment and nobody else appears to report anything similar, you are the only person that's going to be able to troubleshoot it.

You will have to follow this guide (but using Visual Studio 2022 and not Visual Studio 2019) so that you can debug your own compiled version of Zadig on your platform, and tell us where in the code the application crashes.

**Comment by mcuee** [comment]
@lordrak007 

In case you can not get Zadig to work, you may want to try out libusbK's GUI Inf-wizard. It is using an older version of libwdi.
