### ISSUE TITLE
Zadzig problem!

### ISSUE THREAD

**Issue by tavis2000** [pbatard/libwdi#317]
I have a problem. My ACR 122U RFID Reader/Writer is not working anymore. I was told to install zadzig and it replaced the drivers. Is there any way to reset? And to fix my reader/writer? Sorry I'm new to all of this!

**Comment by pbatard** [comment]
https://github.com/pbatard/libwdi/wiki/FAQ#help-zadig-replaced-the-driver-for-the-wrong-device-how-do-i-restore-it
