### ISSUE TITLE
Event: Device not started (BTHUSB)

### ISSUE THREAD

**Issue by 463** [pbatard/libwdi#320]
I got the following information:
```
Beim Start des Geräts USB\VID_0A12&PID_0001\6&29e1b059&0&4 ist ein Problem aufgetreten.

Treibername: bth.inf
Klassen-GUID: {e0cbf06c-cd8b-4647-bb8a-263b43f0f974}
Dienst: BTHUSB
Untere Filter: 
Obere Filter: 
Problem: 0x1F
Problemstatus: 0xC0000001
```
The installation is according to https://www.yuque.com/makeblock-help-center-en/cyberpi/bluetooth-compatibility

The device is not listed as 'Bluetooth Radio'  but as 'CSR8510 A10'. 

It is as bluetooth dongle V5.0. Can this be the reason?

**Comment by pbatard** [comment]
If the driver was successfully installed by Zadig then I'm afraid that whatever issue you are having afterwards has nothing to do with this project. I encourage you to ask questions about a specific device or application on user forums that are related to this device or application, which this bug tracker is not.
