### ISSUE TITLE
Provide shared library binaries in Releases

### ISSUE THREAD

**Issue by Mrcubix** [pbatard/libwdi#321]
I would usually open discussion for things like this but, it is disabled on this repo.

I intended to use libwdi in an application that would be provided by support members to users.
However, it does not seem like this project provides binaries for just the library in its Releases. 

I tried compiling it myself for 3 hours, but the provided guide does not seem to work.
I also tried building it in msys2, which worked out for bigger libraries & projects, but it does not seem like it is working either. 

It keeps complaining about incompatible windows specific libraries, the same way it appears for the maintainer here: https://github.com/pbatard/libwdi/issues/130#issuecomment-400654331.
After reading this issue, i understood that i wouldn't be able to build it in msys2 either.

Would it be possible to start providing the libraries in Releases? Even if it's not an important app, I won't be able to get it started until it happens.

**Comment by pbatard** [comment]
I'm afraid I'm not planning to do that. You can clone the project and use GitHub Actions if you have trouble compiling, and then create your own artifacts as needed. Compilation issues experienced by a minority of people is **not** something I am ever planning to take care of, sorry.
