### ISSUE TITLE
Zadig libusb on Windows 11 issues

### ISSUE THREAD

**Issue by K2AAE** [pbatard/libwdi#325]
I tried to install NUT for my CyberPower UPS, it said it needed libusb so I used Zadig to install libusb, after Zadig installed the libusb drivers I lost the ability to connect to the UPS (plug USB in, it appears as CP1500 UPS but the CyberPower software can't connect). After trying different combinations and drivers I gave up, deleted all INF files with CP1500 (UPS) in them, deleted the driver that shows up when I plug the UPS in, uninstalled the CyberPower software and installed the latest version, it can't connect to the UPS. Every time I plug the UPS in the computer creates a new INF file pointing to the drivers Zadig installed, how do I stop this?

**Comment by pbatard** [comment]
The trick is to insist, as well as make sure you plug your device into every USB port it was ever plugged in and delete the driver each time.

Or, in Device Manager, you can try _View_ &rarr; _Show hidden devices_ and make sure you uninstall all the hidden devices you see that are using the libusb/WinUSB driver.
