### ISSUE TITLE
Windows 11 USBasp installation failed

### ISSUE THREAD

**Issue by Rafalemirage** [pbatard/libwdi#329]
Hello, 

I have been trying to install the driver for a USBasp bootloader but I get an error message. It looks like there is a problem of creating a file if I am not mistaken. I tried disabling my antivirus (Bitdefender) but the problem remains. Does anyone have an idea of what is happening ?

Thanks

Bellow is the log I get :

```
Zadig 2.9.788
Windows 11 Home, x64 (Build 22631.3737)
ini file 'zadig.ini' not found in 'I:\Simulation' - default parameters will be used
default driver set to 'WinUSB'
1 device found.
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_16C0&PID_05DC&REV_0102
libwdi:debug [wdi_create_list] Compatible ID: USB\COMPAT_VID_16C0&Class_00&SubClass_00&Prot_00
libwdi:debug [wdi_create_list] Driverless USB device (12): USB\VID_16C0&PID_05DC\8&26DF9A5D&0&3
libwdi:debug [wdi_create_list] Device description: 'USBasp'
Using inf name: USBasp.inf
Could not extract files
Driver Installation: FAILED (Could not allocate resource)
libwdi:error [extract_binaries] Could not create file 'C:\Users\admin\usb_driver\.\installer_x64.exe' ([0x00000005] Access is denied.)
```

**Comment by pbatard** [comment]
Don't use `Admin` or `Administrator` as a local account. This is not supported and will lead to the kind of access denied issues you see with various applications. You should use a regular account and then use elevation.
