### ISSUE TITLE
How do I make the driver support my controller on windows?

### ISSUE THREAD

**Issue by qinderium** [pbatard/libwdi#331]
Hi, sorry if I sound stupid or if I'm at the wrong page for this but I'm using 'Scpserver' I guess it's called and i want my controller to be able to control my mouse pointer and simple actions like clicking and selecting. Does that driver support it and if so how do I turn that feature on? Thanks so much in advance!

**Comment by pbatard** [comment]
I'm afraid this is the wrong place. This is not a general support forum, but a tracker to log issue with Zadig/libwdi, which your report has nothing to do with.

Please find the maker of the Scpserver and ask them.
