### ISSUE TITLE
Please, please, add a completely dark theme. 

### ISSUE THREAD

**Issue by Raart** [pbatard/libwdi#337]
Not much to add. I ask to add it for the sight impaired, for the professionals staying hours in front of their screens. Windows is becoming infamous for its white flashing opening windows.
It is a shame that each Windows app programmer must spend time for obtaining what is automatic on other platforms.
Thank you for your efforts, it's for good, our health and now to spend fewer energy too.

Andreas

**Comment by pbatard** [comment]
I'm afraid I'm not ever planning to do that myself. I just don't have that kind of time to invest on libwdi for this kind of feature (especially as it's really not that simple to add a dark theme to a **pure GDI win32 application**) and I just can't justify taking time away from other projects.

On the other hand, if someone wants to invest their own time and contribute a dark theme, I'll be happy to integrate a patch.
