### ISSUE TITLE
libwdi inf-wizard: Resource Not found

### ISSUE THREAD

**Issue by pradhr** [pbatard/libwdi#44]
Hi, I am new to libwdi. I have just compiled lidwdi example with Visual Studio Community Edition 2013 and use libusb0 driver. I can compile the project successfully and created inf-wizard.exe file.
When I run the inf-wizard.exe file then at the end it says "Resource Not Found".

If I use the original inf-wizard.exe distributed with libusb0 library then it installs successfully.
But when install newly compiled inf-wizard.exe then it gives this error.

Please guide me, what could be the problem?

I have modified the config.h file for only using libusb0:
```
#ifndef DDK_DIR
//#define DDK_DIR "C:/Program Files (x86)/Windows Kits/8.1"
#endif

/* 64bit subdirectory for WinUSB redist files ("x64" or "amd64") */
#define X64_DIR "x64"

/* embed libusb0 driver files from the following location */
#ifndef LIBUSB0_DIR
#define LIBUSB0_DIR "D:/temp/libusb-win32"
#endif

/* embed libusbK driver files from the following location */
#ifndef LIBUSBK_DIR
//#define LIBUSBK_DIR "D:/libusbK/bin"
#endif

/* embed user defined driver files from the following location */
#ifndef USER_DIR
// #define USER_DIR "C:/signed-driver"
#endif
```

**Comment by pbatard** [comment]
I'm afraid I don't support inf-wizard. It's not something that I wrote, I haven't updated it in years and it has a few issues, so I am planning to remove it altogether from future versions of libwdi.
Please try to use one of the other samples, or post on the libusb-win32 mailing list for help, as they are the people actually maintaining inf-wizard.
