### ISSUE TITLE
How to Trust wdi-simple

### ISSUE THREAD

**Issue by pmartinet** [pbatard/libwdi#59]
Hi everybody,
I'm new with libwdi. I'm trying to install a libusb-win32 driver using wdi-simple while my device is not connected yet, using an NSIS script. When I launch it without any antivirus active on my PC, all is done correctly. But when I Activate antivirus, the driver installation fails due to wdi-simple false positive.
I googled for various threads, but i found no solution to avoid the problem. My goal is to install the driver automatically with no device connected. I'm searching some suggestion to escape this problem.
Eventually, how can I trust wdi-simple?

Any Idea?
Thanks in advance
Best Regards

**Comment by pbatard** [comment]
> But when I Activate antivirus, the driver installation fails due to wdi-simple false positive.

>  I'm searching some suggestion to escape this problem.

You need to report this false positive to your anti virus manufacturer. They all should have a website or e-mail where you can do so.

There's NO other solution.
