### ISSUE TITLE
Detection of remote Device fails on server 2012 hosted on Citrix 

### ISSUE THREAD

**Issue by Webbsolution** [pbatard/libwdi#72]
I am not sure this is something that you can resolve but if you can it would make supporting less than capable users easier :)   

IN the hopes of doing a remote flash leveraging virtual servers in one location and a remote radio in another location I setup a Citrix server. The server uses USB port redirection to detect and communicate with remote USB devices. My horus forexample seems to work fine - I can power it up - connect the local USB and then log into a remote server --- On the server I see all the SD drives of the horus. When I connect it powered down I can install zadig and Zadid sees the St32Boot loader as per instructions. It also installs the driver without error. However when I select a OTX build to flash the radio I get an error 

FIlter on vendor =0x0483 Product=0xdf11
 No DFU Capable USB Device was found

**Comment by pbatard** [comment]
> It also installs the driver without error.

Then I'm sorry, but this is not an issue with Zadig/libwdi, and I will have to close this issue.

Hopefully, you can find help either with Citrix support or the makes of the devices you are trying to access.
