### ISSUE TITLE
Hori Flightstick 3 support.

### ISSUE THREAD

**Issue by HORIFlightstick3** [pbatard/libwdi#86]
Oups iam so sorry wrong page. Someone sup this topic. Thank you.

Hello. Could you add support for the HORI Flightstick 3?
He have no Bluetooth.

I don't know what information you need.

HORI FLIGHTSTICK 3 HP3-110U

He is recognize as Flightstick3.
(VID: 0F0D, PID: 0018)
++Notify [Arrival] [{2F87C733-60E0-4355-8515-95D6978418B2}]

ScpToolkit Error
Couldn't open device \\?
\USB#VID_0F0D&PID_0018#5&2C60A704&0&9#{E2824A09-DBAA-4407-85CA-C8E8FF5F6FFA}

**Comment by pbatard** [comment]
libwdi is only for generic driver installation, using one of the WinUSB, libusb0 or libusbK. As such, I don't "add" support for specific devices, as there's nothing to add.

You need to contact the makers of ScpToolkit if you want support.
