### ISSUE TITLE
Wii U GC Adapter Timeout

### ISSUE THREAD

**Issue by sourtooth** [pbatard/libwdi#87]
I'm trying to configure my Wii U to Gamecube adapter to work on my PC, but Zadig runs for a while then times out whenever I try to follow the steps. I can't find any solution to this issue online, so here I am.

**Comment by pbatard** [comment]
Options &rarr; Advanced Mode, then try again and make sure to copy your __full log__.

Without a log it's impossible to help you out.

**Comment by pbatard** [comment]
No log &rarr; Closed.
