### ISSUE TITLE
cant install/reinstall/replace driver?

### ISSUE THREAD

**Issue by gipsarYT** [pbatard/libwdi#89]
it says in the bottom `driver installation: FAILED (Could not allocate resource)`
and in advanced it says
```
Using inf name: USB_Camera-B4.09.24.1_(Interface_0).inf
Could not extract files
Driver Installation: FAILED (Could not allocate resource)
libwdi:info [wdi_prepare_driver] K driver available - adding the libusbK DLLs to the libusb-win32 inf
libwdi:error [extract_binaries] failed to create file 'C:\Users\cjolson80\usb_driver\.\installer_x64.exe' ([#00000020] The process cannot access the file because it is being used by another process.)
```
i am trying to replace driver with libusb-win32 because i installed the wrong driver on accident and now zadig isn't working at all!

**Comment by pbatard** [comment]
Try to reboot your machine. If this doesn't work, please make sure you are attempting to install the drive in Advanced Mode and copy/paste your __FULL__ log.
