### ISSUE TITLE
How to return driver to previous state

### ISSUE THREAD

**Issue by saikyou11** [pbatard/libwdi#90]
![device doesn t start there s a non-existent device stated](https://user-images.githubusercontent.com/29733878/27593578-cea4ac12-5b57-11e7-8861-e80414a4584a.png)
![picture device manager](https://user-images.githubusercontent.com/29733878/27593593-d30cb13c-5b57-11e7-8684-fcab5bb6af17.png)

Hello, 

I'm used my internal Bluetooth to replace the driver.
Now I am not able to use the Bluetooth anymore.
Does anyone know how to change it back to the original state?
When I go to device manager there's a yellow triangle and when I click the wireless Bluetooth it says: this device is nonexisting,

Thanks in regard

Ps. Sorry that the pictures are in Dutch

**Comment by pbatard** [comment]
You should download the bluetooth driver from your manufacturer's web site and install it.
