### ISSUE TITLE
Zadig won't detect my GC adapter

### ISSUE THREAD

**Issue by thatdumpster** [pbatard/libwdi#98]
Heya. I've been trying to play dolphin for the past couple of days but my controller won't work, as Zadig doesn't detch WUP-028. I've tried as many things as a non computer savvy person can try and can't seem to figure it out. Any help?

**Comment by pbatard** [comment]
I think you should try to get help in GameCube dedicated forums. Zadig is a generic driver installer, and as such, there's very little advice that can be provided for specific devices.
